# Generic code to customize for the project
name: Build and Upload Release Artifact

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Java configuration
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      # JAR artifact building
      - name: Build with Maven
        run: mvn -e clean package

      # List generated files (debugging)
      - name: List target directory
        run: ls -lhtr target/

      # Zip artifact
      - name: Zip JAR file
        run: zip hermod-gippity.jar target/*.jar

      # Upload artifact on release
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            hermod-gippity.zip
